server:
  port: 6014
  #session的超时时间
  servlet:
    session:
      timeout: 3600

spring:
  application:
    name: PORTAL-SERVER
  servlet:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb
      file-size-threshold: 10Mb

springsecurity:
  remberme: true



