#jpa-mysql的配置 为了打印mysql的sql语句
spring:
      jpa: 
        database: MYSQL
        show-sql: true
        properties: 
           hibernate: 
              dialect: org.hibernate.dialect.MySQL5Dialect
        hibernate: 
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy